### ISSUE TITLE
bundle sometimes fails

### ISSUE THREAD

**Issue by fdev31** [rubik/pyg#62]
Running the following command:

```
pyg bundle bee.pyb zicbee zicbee-mplayer zicbee-vlc zicbee-gst
```

I get the following error:

```
AttributeError: 'ReqManager' object has no attribute 'downloaded_name'
```

With the following manager content:

```
{'pref': ['.tar.gz', '.tar.bz2', '.zip', '.egg'], 'req': Requirement(mutagen>=1.20), 'package_manager': <PyPIJson[mutagen] object at 154913420>, 'name': 'mutagen'}
```

**Comment by rubik** [comment]
Argh! Yeah that's because Pyg searches, for the given package name, some files hosted on PyPI (through PyPI's Json API) to download. Since `mutagen` doesn't have any files on PyPI, Pyg cannot download anything. It should be easy to fix: I will use `get_links` function to find additional links.

Thank you for your interest,
rubik

**Comment by rubik** [comment]
Ok, I fixed this one. The problem was that `buzhug` package have a download url like:
https://downloads.sourceforge.net/project/buzhug/buzhug/buzhug-1.8/buzhug-1.8.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fbuzhug%2Ffiles%2F&ts=1285445021&use_mirror=switch

and Pyg didn't manage to get package version, file-type, etc. but I fixed that with `urlparse`.

rubik

**Comment by rubik** [comment]
Can you try whether Pyg works on your pc? On mine it works.

**Comment by fdev31** [comment]
Works well for me

**Comment by rubik** [comment]
Well, very good!!
